spring:
  application:
    name: graduation-process-management
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 10000
  jackson:
    default-property-inclusion: non_null

mybatis-plus:
  configuration:
    database-id: assign_id

logging:
  level:
    root: warn
    com:
      nefu: debug
  pattern:
    console: logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %C.%M[%line] - %msg%n
server:
  port: 8080

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/mybatistest?serverTimezone=Asia/Shanghai
    username: root
    password: root

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/graduation_management?createDatabaseIfNotExist=true?serverTimezone=Asia/Shanghai
    username: root
    password: root
    initialization-mode: always
    schema: classpath:schema-mysql.sql
logging:
  level:
    root: warn
    com:
      nefu: info
