spring:
  application:
    name: graduation-process-management
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/graduation_process_management?serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      connection-timeout: 10000
  jackson:
    default-property-inclusion: non_null

logging:
  level:
    root: warn
    com:
      nefu: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'
server:
  port: 8080
my:
  secretkey: R28K42ZEJ8LWRHU5
  salt: 636eac2534bcfcb0
  upload: D:/upload

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/graduation_process_management?createDatabaseIfNotExist=true?serverTimezone=Asia/Shanghai
    username: root
    password: root
    initialization-mode: always
    schema: classpath:schema-mysql.sql
my:
  secretkey: R28K42ZEJ8LWRHU5
  salt: 636eac2534bcfcb0
  upload: {upload}
logging:
  level:
    com:
      nefu: info
